### ISSUE TITLE
Bootstrap, jquery y fontawesome

### ISSUE THREAD

**Issue by aitorbouzas** [PabloLarrie/StepByStep#2]
No es necesario descargarse y meter en tu repositorio todos los archivos para que estas librerías funcionen, puedes hacer link desde el HTML para que se lo descargue automáticamente sin necesidad de tenerlo en local.

jQuery + Bootstrap:
https://getbootstrap.com/docs/4.3/getting-started/introduction/#css

Fontawesome:
https://fontawesome.com/v4.7.0/get-started/

**Comment by PabloLarrie** [comment]
Qué quieres decir?

**Comment by aitorbouzas** [comment]
Si lees los enlaces que te puse, verás que pone que con tener `<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> ` en el `<head>` de tu HTML ya es suficiente para que funcione bootstrap en toda tu página, sin embargo, tú has subido una copia del repositorio de bootstrap completo, que es muy grande: https://github.com/PabloLarrie/StepByStep/tree/main/core/static/core/vendor/bootstrap

**Comment by aitorbouzas** [comment]
Fixed in #3
